//https://marketplace.visualstudio.com/items?itemName=humao.rest-client

GET http://localhost:8080/api/todo HTTP/1.1

###
POST http://localhost:8080/api/todo HTTP/1.1
content-type: application/json

{
    "title": "Task 2"
}

###
GET http://localhost:8080/api/todo/691f5cd0911bc0e1b9ddafc4 HTTP/1.1



###
PUT http://localhost:8080/api/todo/691f5cd0911bc0e1b9ddafc4 HTTP/1.1
content-type: application/json

{
    "completed": true
}


###
DELETE http://localhost:8080/api/todo/691f5cd0911bc0e1b9ddafc4 HTTP/1.1